server:
  port: 8081
  servlet:
    context-path: /

cors:
  allowed-origins: http://localhost:3000

springdoc:
  packages-to-scan: com.example.spring.controller

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: sample_restaurants